### ISSUE TITLE
httpAuth HTTP authentication: unsupported scheme 'token'

### ISSUE THREAD

**Issue by eswenson1** [softwaremill/realworld-tapir-zio#110]
I'm unable to use the POST APIs. I attempt Authentication by pressing the Authenticate button in the swagger UI, and I get a dialog box that says:

```
Available Authorizations:

httpAuth HTTP authentication: unsupported scheme 'token'
```

What do I need to do?

**Comment by wydra98** [comment]
Yes, we are aware of this problem. We use Swagger for documentation purposes, however, it does not support user authorization. The issue arises because the RealWorld documentation (found at https://realworld-docs.netlify.app/docs/specs/backend-specs/endpoints) specifies the use of a header in the request, starting with 'Token' instead of common formats like 'Bearer.' Unfortunately, Swagger does not support the 'Token' format, resulting in this error.   

Therefore, we recommend using Swagger solely for documentation purposes, and for sending requests, you should use Postman with a collection of requests imported from this site: https://raw.githubusercontent.com/gothinkster/realworld/main/api/Conduit.postman_collection.json. More information about tests and requests in the RealWorld you can find here: https://realworld-docs.netlify.app/docs/specs/backend-specs/postman.

**Comment by adamw** [comment]
@wydra98 is this a known problem of the RW spec? something that has been raised as an issue on their side?

**Comment by wydra98** [comment]
@adamw yes, there is an open issue in the RealWord project: https://github.com/gothinkster/realworld/issues/81

**Comment by adamw** [comment]
@wydra98 Thanks, always good to link if there's an existing issue :) Maybe we can support both as well?

**Comment by eswenson1** [comment]
> Therefore, we recommend using Swagger solely for documentation purposes, and for sending requests, you should use

Thanks much, I'll do that.
